spring:
  application:
    name: PCI-IVR
server:
  port: 8080
eureka:
  client:
    enabled: false #WE DO NOT WANT TO RUN THE EUREKA SERVER IN THE DEVELOPMENT MACHINE
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
com:
  oup:
    pciivr:
      sap:
        username: CAMELPCIIVR
        password: PCI@camel11
        serverurl: betsgill.uk.oup.com
        sysnr: 00
        client: 30
---
spring:
  profiles: dev
server:
  port: 10081
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://dev-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: false
com:
  oup:
    pciivr:
      sap:
        username: CAMELPCIIVR
        password: PCI@camel11
        serverurl: betsgill.uk.oup.com
        sysnr: 00
        client: 30
---
spring:
  profiles: uat
server:
  port: 10081
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://uat-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: false
com:
  oup:
    pciivr:
      sap:
        username: CAMELPCIIVR
        password: PCI@camel11
        serverurl: petteril.uk.oup.com
        sysnr: 00
        client: 10
---
spring:
  profiles: prod
server:
  port: 10081
eureka:
  client:
    enabled: true
    service-url:  
      defaultZone: http://prod-oupeureka:8761/eureka/
  instance:
    prefer-ip-address: false
com:
  oup:
    pciivr:
      sap:
        username: CAMELPCIIVR
        password: PCI@camel11
        serverurl: petteril.uk.oup.com
        sysnr: 00
        client: 10